<!-- generated by http://loading.io/ -->

<template>
    <div class="uil-squares-css" v-if="workInProgress">
        <div>
            <div></div>
        </div>
        <div>
            <div></div>
        </div>
        <div>
            <div></div>
        </div>
        <div>
            <div></div>
        </div>
        <div>
            <div></div>
        </div>
        <div>
            <div></div>
        </div>
        <div>
            <div></div>
        </div>
        <div>
            <div></div>
        </div>
    </div>
</template>

<script>
    import {mapState} from 'vuex'

    export default {
        computed: {
            ...mapState([
                'workInProgress'
            ])
        }
    }
</script>

<style lang="css">
    .uil-squares-css {
        margin: 0 auto;
        transform: scale(0.5);
    }

    @-webkit-keyframes uilsquare {
        0% {
            background-color: #333333;
        }
        1% {
            background-color: #bbbbbb;
        }
        11% {
            background-color: #bbbbbb;
        }
        21% {
            background-color: #333333;
        }
        100% {
            background-color: #333333;
        }
    }

    @-webkit-keyframes uilsquare {
        0% {
            background-color: #333333;
        }
        1% {
            background-color: #bbbbbb;
        }
        11% {
            background-color: #bbbbbb;
        }
        21% {
            background-color: #333333;
        }
        100% {
            background-color: #333333;
        }
    }

    @-moz-keyframes uilsquare {
        0% {
            background-color: #333333;
        }
        1% {
            background-color: #bbbbbb;
        }
        11% {
            background-color: #bbbbbb;
        }
        21% {
            background-color: #333333;
        }
        100% {
            background-color: #333333;
        }
    }

    @-ms-keyframes uilsquare {
        0% {
            background-color: #333333;
        }
        1% {
            background-color: #bbbbbb;
        }
        11% {
            background-color: #bbbbbb;
        }
        21% {
            background-color: #333333;
        }
        100% {
            background-color: #333333;
        }
    }

    @-moz-keyframes uilsquare {
        0% {
            background-color: #333333;
        }
        1% {
            background-color: #bbbbbb;
        }
        11% {
            background-color: #bbbbbb;
        }
        21% {
            background-color: #333333;
        }
        100% {
            background-color: #333333;
        }
    }

    @-webkit-keyframes uilsquare {
        0% {
            background-color: #333333;
        }
        1% {
            background-color: #bbbbbb;
        }
        11% {
            background-color: #bbbbbb;
        }
        21% {
            background-color: #333333;
        }
        100% {
            background-color: #333333;
        }
    }

    @-o-keyframes uilsquare {
        0% {
            background-color: #333333;
        }
        1% {
            background-color: #bbbbbb;
        }
        11% {
            background-color: #bbbbbb;
        }
        21% {
            background-color: #333333;
        }
        100% {
            background-color: #333333;
        }
    }

    @keyframes uilsquare {
        0% {
            background-color: #333333;
        }
        1% {
            background-color: #bbbbbb;
        }
        11% {
            background-color: #bbbbbb;
        }
        21% {
            background-color: #333333;
        }
        100% {
            background-color: #333333;
        }
    }

    .uil-squares-css {
        background: none;
        position: relative;
        width: 200px;
        height: 200px;
    }

    .uil-squares-css div {
        position: absolute;
        z-index: 1;
        width: 40px;
        height: 40px;
        background-color: #333333;
    }

    .uil-squares-css div > div {
        position: absolute;
        top: 0;
        left: 0;
        -ms-animation: uilsquare 1.5s linear infinite;
        -moz-animation: uilsquare 1.5s linear infinite;
        -webkit-animation: uilsquare 1.5s linear infinite;
        -o-animation: uilsquare 1.5s linear infinite;
        animation: uilsquare 1.5s linear infinite;
        width: 40px;
        height: 40px;
    }

    .uil-squares-css > div:nth-of-type(1) {
        top: 30px;
        left: 30px;
    }

    .uil-squares-css > div:nth-of-type(1) > div {
        -ms-animation-delay: 0s;
        -moz-animation-delay: 0s;
        -webkit-animation-delay: 0s;
        -o-animation-delay: 0s;
        animation-delay: 0s;
    }

    .uil-squares-css > div:nth-of-type(2) {
        top: 30px;
        left: 80px;
    }

    .uil-squares-css > div:nth-of-type(2) > div {
        -ms-animation-delay: 0.1875s;
        -moz-animation-delay: 0.1875s;
        -webkit-animation-delay: 0.1875s;
        -o-animation-delay: 0.1875s;
        animation-delay: 0.1875s;
    }

    .uil-squares-css > div:nth-of-type(3) {
        top: 30px;
        left: 130px;
    }

    .uil-squares-css > div:nth-of-type(3) > div {
        -ms-animation-delay: 0.375s;
        -moz-animation-delay: 0.375s;
        -webkit-animation-delay: 0.375s;
        -o-animation-delay: 0.375s;
        animation-delay: 0.375s;
    }

    .uil-squares-css > div:nth-of-type(4) {
        top: 80px;
        left: 130px;
    }

    .uil-squares-css > div:nth-of-type(4) > div {
        -ms-animation-delay: 0.5625s;
        -moz-animation-delay: 0.5625s;
        -webkit-animation-delay: 0.5625s;
        -o-animation-delay: 0.5625s;
        animation-delay: 0.5625s;
    }

    .uil-squares-css > div:nth-of-type(5) {
        top: 130px;
        left: 130px;
    }

    .uil-squares-css > div:nth-of-type(5) > div {
        -ms-animation-delay: 0.75s;
        -moz-animation-delay: 0.75s;
        -webkit-animation-delay: 0.75s;
        -o-animation-delay: 0.75s;
        animation-delay: 0.75s;
    }

    .uil-squares-css > div:nth-of-type(6) {
        top: 130px;
        left: 80px;
    }

    .uil-squares-css > div:nth-of-type(6) > div {
        -ms-animation-delay: 0.9375s;
        -moz-animation-delay: 0.9375s;
        -webkit-animation-delay: 0.9375s;
        -o-animation-delay: 0.9375s;
        animation-delay: 0.9375s;
    }

    .uil-squares-css > div:nth-of-type(7) {
        top: 130px;
        left: 30px;
    }

    .uil-squares-css > div:nth-of-type(7) > div {
        -ms-animation-delay: 1.125s;
        -moz-animation-delay: 1.125s;
        -webkit-animation-delay: 1.125s;
        -o-animation-delay: 1.125s;
        animation-delay: 1.125s;
    }

    .uil-squares-css > div:nth-of-type(8) {
        top: 80px;
        left: 30px;
    }

    .uil-squares-css > div:nth-of-type(8) > div {
        -ms-animation-delay: 1.3125s;
        -moz-animation-delay: 1.3125s;
        -webkit-animation-delay: 1.3125s;
        -o-animation-delay: 1.3125s;
        animation-delay: 1.3125s;
    }
</style>
