export const mutations = {
    BEGIN_WORK_IN_PROGRESS: 'BEGIN_WORK_IN_PROGRESS',
    END_WORK_IN_PROGRESS: 'END_WORK_IN_PROGRESS',

    MARK_CONTACT_FORM_AS_SENT: 'MARK_CONTACT_FORM_AS_SENT',
};

export const actions = {};
